config/routes.rb
Rails.application.routes.draw do 

  resources :payment_notifications
  # current_cart 'cart', :controller => 'carts', :action => 'show', :id => 'current'
  
  get '/carts', to: 'carts#show', as: 'current_cart'
  get '/line_items', to: 'line_items#create_line_item', as: 'create_current_cart'
  resources :products
  resources :categories
  # resources :line_items
  resources :carts

  # get 'errors/internal_server_error'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users, only: [:index, :show,:update]
  # match 'current_cart', :to => "carts#show", :via => :all 
  
  # resources :products
  # resources :categories
  # resources :accounts
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	mount_uploader :image, ImageUploader
	mount_uploaders :attachments, ImageUploader
	validates :image, file_size: { less_than: 1.megabytes }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :image,:category_id, :remove_image, :image_cache, :remote_image_url,attachments: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- < %= render 'shared/errors', object: post %> -->
  <div class="field">
    <%= form.label :category_id %><br />
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %><br>
    <%= form.text_field :remote_image_url %>
    <small>Enter URL to an image</small>
    <%= form.hidden_field :image_cache %>
  </div>

  <% if product.image? %>
    <%= image_tag product.image.thumb.url %>
    <div>
      <%= label_tag :remove_image do %>
        Remove image
        <%= form.check_box :remove_image %>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :attachments %>
    <%= form.file_field :attachments, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
      <th>Add to Cart</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= product.category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <% if can? :update, @product %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <% end %>
        <% if can? :destroy, @product %>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td class="actions">
          <%= link_to "Add to Cart", create_current_cart_path(:product_id => product), :method => :post %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <%= link_to(image_tag(@product.image.thumb.url, alt: 'Image'), @product.image.url, target: '_blank') if @product.image? %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<% unless @product.category.nil? %>
	<p>
	  <strong>Category:</strong>
	  <%= link_to h(@product.category.name), @product.category %>
	</p>
<% end %>

<% if @product.attachments? %>
  <p>
    <ul>
      <% @product.attachments.each do |attachment| %>
        <li><%= link_to(image_tag(attachment.thumb.url, alt: 'Image'), attachment.url, target: '_blank') %></li>
      <% end %>
    </ul>
  </p>
<% end %>

<% if can? :update, @product %>
  <%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>
<%= link_to 'Back', products_path %>