config/routes.rb
Rails.application.routes.draw do 

  resources :payment_notifications
  # current_cart 'cart', :controller => 'carts', :action => 'show', :id => 'current'
  
  get '/carts', to: 'carts#show', as: 'current_cart'
  get '/line_items', to: 'line_items#create_line_item', as: 'create_current_cart'
  resources :products
  resources :categories
  # resources :line_items
  resources :carts

  # get 'errors/internal_server_error'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users, only: [:index, :show,:update]
  # match 'current_cart', :to => "carts#show", :via => :all 
  
  # resources :products
  # resources :categories
  # resources :accounts
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end

  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end
  
  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %> alert-dismissable">
  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <%= value %>
	</div>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_url %>">Memespace</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li id="users-link"><a href="<%= users_path %>">Users</a></li>
          <% if current_user %>
            <li id="profile-link"><a href="<%= user_path(current_user) %>">Profile</a></li>
            <li id="profile-link"><a href="<%= categories_path %>">Category</a></li>
            <li id="profile-link"><a href="<%= products_path %>">Product</a></li>
            <li id="profile-link"><a href="<%= carts_path %>">Carts</a></li>
            
            <li><a href="<%= destroy_user_session_path %>">Log Out</a></li>
          <% else %>
            <li><a href="<%= new_user_session_path %>">Log In</a></li>
          <% end %>
        </ul>
      </div>
    </div>
</nav>
<script>
 <% if request.original_url == users_url %>
   $('#users-link').addClass('active');
 <% elsif current_user && request.original_url == user_url(current_user) %>
   $('#profile-link').addClass('active');
 <% end %>
</script>


 <!--  <nav class="navbar navbar-default">
        <div class="navbar-header">
          < %= link_to 'Connect to Harbinger Accounts', root_path, class: 'navbar-brand' %>
        </div>
        <div class="pull-right right-buttons">
          < % if user_signed_in? %>
          < %= link_to 'Sign out',  destroy_user_session_path , method: 'delete', class: 'btn btn-default navbar-btn' %>
          < % else %>
            < %= link_to 'Sign in',  new_user_session_path , method: 'delete', class: 'btn btn-default navbar-btn' %>
          < % end %>
        </div>
      </nav>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostgresApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="container">
      <!-- < %= render 'layouts/flash_messages' %>-->
      <%= render 'layouts/menu' %> 
      
    </header>

    <div class="container">
      <%= flash_messages if show_layout_flash? %>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>